### ISSUE TITLE
两个视频同时播，不行

### ISSUE THREAD

**Issue by CookieCzy** [DevlinChiu/dcplayer#4]
两个视频同时播，只有一个是正常的。

**Comment by DevlinChiu** [comment]
这是因为我在IjkVideoView中对音频焦点（AudioFocus）进行监听，如果有另外一个播放器获取了音频焦点，正在播放的播放器将暂停播放，如果想两个播放器同时播放，只需将音频焦点监听相关代码去除即可

**Comment by yuger** [comment]
RecyclerView列表播放视频addOnChildAttachStateChangeListener()当滑出屏幕视频停止播放，滑回再次点击刚才停止的视频无效，不能继续播放。

**Comment by dueeeke** [comment]
@yuger 已经修复，感谢反馈

**Comment by yuger** [comment]
还有一个问题，RecyclerView的onBindViewHolder()似乎捕捉不到holder.itemView的点击事件，而我需要在点击某项时去请求播放地址，https://github.com/dueeeke/dkplayer/blob/master/app/src/main/java/com/dueeeke/dkplayer/adapter/VideoRecyclerViewAdapter.java#L51 你这里是写死的，该咋整啊

**Comment by dueeeke** [comment]
@yuger 继承IjkVideoView, 重写start()方法，请求到地址后，重新设置地址，再调用super.start()开始播放
